In [1]:
countdown = [4,3,2,1,0]
for number in countdown:
    print(number)

4
3
2
1
0


In [3]:
from time import sleep
countdown = [4,3,2,1,0]
for number in countdown:
    print(number)
    sleep(2) # sleep is use fior time delay

4
3
2
1
0


In [5]:
for i in range(10,20,2):
    print(i)

10
12
14
16
18


In [7]:
for i in range(50):
    if i==10:
        break
    print(i)

0
1
2
3
4
5
6
7
8
9


In [9]:
for i in range(5):
    if i == 2:
        continue # except 2 that means 2 will remove
    print(i)

0
1
3
4


In [14]:
def distance_from_earth(destination):
    if destination =="moon":
        return "238,855"
    else:
        return "unable to compute to that destination"
distance_from_earth("moon")

'238,855'

In [15]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0





Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\ASUS\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.12.12 |       haa95532_0         127 KB
    certifi-2023.11.17         |  py311haa95532_0         160 KB
    openssl-3.0.12             |       h2bbff1b_0         7.4 MB
    ------------------------------------------------------------
                                           Total:         7.7 MB

The following packages will be UPDATED:

  ca-certificates                     2023.08.22-haa95532_0 --> 2023.12.12-haa95532_0 
  certifi                         2023.7.22-py311haa95532_0 --> 2023.11.17-py311haa95532_0 
  openssl                                 3.0.10-h2bbff1b_2 --> 3.0.12-h2bbff1b_0 




ca-certificates-2023 | 127 KB    |            |   0% 

certifi-2023.11.17

In [19]:
import numpy as np
a=np.array([1,2,3,4,])
print(a)
b=np.zeros(3,int)
print(b)
c=np.zeros_like(a)
print(c)

[1 2 3 4]
[0 0 0]
[0 0 0 0]


In [20]:
import numpy as np
a=np.arange(0,100,5)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [21]:
import numpy as np
a=np.arange(12)
np.reshape(a,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
import numpy as np
a=np.arange(12)
print(a[[1,4,7,0]])

[1 4 7 0]


In [ ]:
stop_words = { 'i', 'me', 'my', 'myself', 'we', 'out', 'ours', 'ourselves', 'you', 'your', 'yours', 
              'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'herself', 'it', 
              'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that'}

def remove_stopwords(file_path, output_path):
    with open(file_path, 'r') as file:
        text = file.read()
        words = text.split()
        filtered_words = [word for word in words if word.lower() not in stop_words]
        filtered_text = ' '.join(filtered_words)

        with open(output_path, 'w') as output_file:
            output_file.write(filtered_text)

input_file_path = 'input.txt'
output_file_path = 'output.txt'

remove_stopwords(input_file_path, output_file_path)
print(f'Stop words removed. Results saved to {output_file_path}')
